image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- dotnet tool install --global Codecov.Tool

build:
  project: BooruSharp.sln

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[BooruSharp*]* -[BooruSharp.UnitTests*]*" -output:"coverage.xml" -oldstyle
- codecov -f "coverage.xml"