name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 1 1 * * *

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup Chocolatey
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: -h
    - name: Install dependencies
      run: dotnet restore
    - name: Install OpenCover
      run: choco install opencover.portable
    - name: Install Codecov
      run: choco install codecov
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[BooruSharp*]* -[BooruSharp.UnitTests*]*" -output:"coverage.xml" -oldstyle
    - name: Upload coverage
      run: codecov -f "coverage.xml"
